#!/bin/bash
# file name postinst
# Post-install script

sudo bash -c "echo '[Desktop Entry]
Version=1.0.0.0
GenericName[ru]=BuxarVideoUploader
Name=BuxarVideoUploader
Comment=BuxarVideoUploader
Icon=/usr/share/BuxarVideoUploader/dist/Application/icon.ico
Exec=sh -c \"cd /usr/share/BuxarVideoUploader/dist/Application && ./Application\"
Terminal=false
StartupWMClass=Application
Categories=Network;FileTransfer;
Type=Application' > /usr/share/applications/BuxarVideoUploader.desktop"

FILE=/usr/lib/x86_64-linux-gnu/libxcb-util.so.1

sudo chmod a+x /usr/share/BuxarVideoUploader/dist/Application/Application

if [ ! "$FILE" ]; then
    sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb-util.so.0 /usr/lib/x86_64-linux-gnu/libxcb-util.so.1
fi
