#!/bin/bash

FILE=/usr/share/applications/BuxarVideoUploader.desktop

if [ "$FILE" ]; then
sudo rm /usr/share/applications/BuxarVideoUploader.desktop
fi

FILE=/usr/share/BuxarVideoUploader

if [ "$FILE" ]; then
sudo rm /usr/share/BuxarVideoUploader
fi