#!/bin/bash
# file name postinst
# Post-install script

sudo bash -c "echo '[Desktop Entry]
Version=1.0.0
Name=BuxarVideoUploader
Comment=BuxarVideoUploader
Icon=/usr/share/BuxarVideoUploader/dist/Application/icon.png
Exec=sh -c \"cd /usr/share/BuxarVideoUploader/dist/Application && ./Application\"
Terminal=false
StartupWMClass=Application
Type=Application' > /usr/share/applications/BuxarVideoUploader.desktop"

sudo apt-get install build-essential
sudo apt install -y zlib1g-dev zlibc
sudo apt install -y libssl-dev
sudo apt install -y libssl1.1 || sudo apt install -y libssl1.0
sudo apt-get install libxcb-xinerama0